/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import entidades.*;
import operaciones.*;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-37
 */
public class JFrameNuevoLibro extends javax.swing.JFrame {
    Validaciones val;
    OperacionesLibro  oper;
    /**
     * Creates new form JFrameNuevoLibro
     */
    public JFrameNuevoLibro() {
        initComponents();
        jPanelImpreso.setVisible(true);
        jPanelElectronico.setVisible(false);
        jTextFieldInteractivo.setEnabled(false);
        oper = new OperacionesLibro();
        val = new Validaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPasta = new javax.swing.ButtonGroup();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<String>();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldIsbn = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelNumPaginas = new javax.swing.JLabel();
        jSpinnerNumPaginas = new javax.swing.JSpinner();
        jLabelAutorPrincipal = new javax.swing.JLabel();
        jComboBoxAutorPrincipal = new javax.swing.JComboBox<String>();
        jPanelImpreso = new javax.swing.JPanel();
        jLabelTipoDePasta = new javax.swing.JLabel();
        jRadioButtonPastaDura = new javax.swing.JRadioButton();
        jRadioButtonPastaSuave = new javax.swing.JRadioButton();
        jLabelPastaSeleccionada = new javax.swing.JLabel();
        jPanelElectronico = new javax.swing.JPanel();
        jLabelTamanoArchivo = new javax.swing.JLabel();
        jSpinnerTamañoArchivo = new javax.swing.JSpinner();
        jCheckBoxEsIteractivo = new javax.swing.JCheckBox();
        jTextFieldInteractivo = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipo.setText("Tipo:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Impreso", "Electronico" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });

        jLabelISBN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelISBN.setText("ISBN:");

        jTextFieldIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIsbnKeyTyped(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTitulo.setText("Título:");

        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabelNumPaginas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNumPaginas.setText("Número de Páginas:");

        jSpinnerNumPaginas.setModel(new javax.swing.SpinnerNumberModel(10, 10, 1000, 1));

        jLabelAutorPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAutorPrincipal.setText("Autor principal:");

        jComboBoxAutorPrincipal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Autor 1", "Autor 2", "Autor 3", "Autor 4" }));

        jPanelImpreso.setBackground(new java.awt.Color(255, 204, 204));
        jPanelImpreso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libro Impreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelTipoDePasta.setText("Tipo de Pasta:");

        buttonGroupTipoPasta.add(jRadioButtonPastaDura);
        jRadioButtonPastaDura.setText("Dura");
        jRadioButtonPastaDura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonPastaDuraStateChanged(evt);
            }
        });

        buttonGroupTipoPasta.add(jRadioButtonPastaSuave);
        jRadioButtonPastaSuave.setText("Suave");
        jRadioButtonPastaSuave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonPastaSuaveStateChanged(evt);
            }
        });

        jLabelPastaSeleccionada.setText(".........");

        javax.swing.GroupLayout jPanelImpresoLayout = new javax.swing.GroupLayout(jPanelImpreso);
        jPanelImpreso.setLayout(jPanelImpresoLayout);
        jPanelImpresoLayout.setHorizontalGroup(
            jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImpresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipoDePasta)
                .addGap(18, 18, 18)
                .addGroup(jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPastaSeleccionada)
                    .addGroup(jPanelImpresoLayout.createSequentialGroup()
                        .addComponent(jRadioButtonPastaDura)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPastaSuave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelImpresoLayout.setVerticalGroup(
            jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImpresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelImpresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDePasta)
                    .addComponent(jRadioButtonPastaDura)
                    .addComponent(jRadioButtonPastaSuave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabelPastaSeleccionada))
        );

        jPanelElectronico.setBackground(new java.awt.Color(204, 204, 255));
        jPanelElectronico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libro Electrónico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabelTamanoArchivo.setText("Tamaño del archivo: ");

        jSpinnerTamañoArchivo.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.30000001192092896d, 100.0d, 0.5d));

        jCheckBoxEsIteractivo.setText("Es interactivo?");
        jCheckBoxEsIteractivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxEsIteractivoStateChanged(evt);
            }
        });
        jCheckBoxEsIteractivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEsIteractivoActionPerformed(evt);
            }
        });

        jTextFieldInteractivo.setText("Escribe aquí bebé ;)");

        javax.swing.GroupLayout jPanelElectronicoLayout = new javax.swing.GroupLayout(jPanelElectronico);
        jPanelElectronico.setLayout(jPanelElectronicoLayout);
        jPanelElectronicoLayout.setHorizontalGroup(
            jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElectronicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTamanoArchivo)
                    .addComponent(jCheckBoxEsIteractivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerTamañoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInteractivo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelElectronicoLayout.setVerticalGroup(
            jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElectronicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTamanoArchivo)
                    .addComponent(jSpinnerTamañoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelElectronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelElectronicoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldInteractivo))
                    .addComponent(jCheckBoxEsIteractivo)))
        );

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelISBN)
                                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldTitulo)
                                    .addComponent(jTextFieldIsbn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNumPaginas)
                                    .addComponent(jLabelAutorPrincipal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAutorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanelImpreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelISBN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumPaginas)
                    .addComponent(jSpinnerNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorPrincipal)
                    .addComponent(jComboBoxAutorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        int indiceSeleccionado = jComboBoxTipo.getSelectedIndex();
        if (indiceSeleccionado == 0) {
            //Libro Impreso
            jPanelImpreso.setVisible(true);
            jPanelElectronico.setVisible(false);
        }else{
            //Libro Electronico
            jPanelImpreso.setVisible(false);
            jPanelElectronico.setVisible(true);
        }

// TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jRadioButtonPastaDuraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonPastaDuraStateChanged
        if(jRadioButtonPastaDura.isSelected()){
        jLabelPastaSeleccionada.setText(jRadioButtonPastaDura.getText());
    }       
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPastaDuraStateChanged

    private void jRadioButtonPastaSuaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonPastaSuaveStateChanged
        if(jRadioButtonPastaSuave.isSelected()){
        jLabelPastaSeleccionada.setText(jRadioButtonPastaSuave.getText());
        }               
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPastaSuaveStateChanged

    private void jCheckBoxEsIteractivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEsIteractivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEsIteractivoActionPerformed

    private void jCheckBoxEsIteractivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxEsIteractivoStateChanged
        if(jCheckBoxEsIteractivo.isSelected()){
            jTextFieldInteractivo.setEnabled(true);
        }else{
            jTextFieldInteractivo.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEsIteractivoStateChanged

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        // TODO add your handling code here:
        
        this.Guardar_Libro();
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    
    int contCaracteres=0;
    private void jTextFieldIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIsbnKeyTyped
     /*
        if (this.jTextFieldIsbn.getText().length()>=13){
         evt.consume();
        }        
        
        char uso = evt.getKeyChar();
        if((uso<'0' || uso>'9')&&(uso!=(char)KeyEvent.VK_BACKSPACE)&&(uso!=(char)KeyEvent.VK_DELETE) &&(uso!=(char)KeyEvent.VK_ENTER)){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Solo se permiten Números","SIUG", JOptionPane.INFORMATION_MESSAGE);
    }*/
       
        Character ch = evt.getKeyChar();
        
        if (!Character.isDigit(ch)){
         evt.consume();
         JOptionPane.showMessageDialog(this, "SOLO INGRESE NUMEROS");
        }
        else{
            if (this.jTextFieldIsbn.getText().length()>=13 ){
                evt.consume();
                JOptionPane.showMessageDialog(this, "EL TAMAÑO MAXIMO ES DE 13 CARACTERES");
            } 
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIsbnKeyTyped

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
       boolean res = val.solo_letras(evt.getKeyChar());
        
       if(!res){
           JOptionPane.showMessageDialog(this, "SOLO INGRESE LETRAS");
           evt.consume();
       }
        
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    public void Guardar_Libro(){
 
        if (jTextFieldIsbn.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ESCRIBA UN ISBN");
           
        }
        
        String isbn= jTextFieldIsbn.getText();
        String tit= jTextFieldTitulo.getText();
        int np = (int)jSpinnerNumPaginas.getValue();
        String autor= (String) this.jComboBoxAutorPrincipal.getSelectedItem();
        Autor au= new Autor();
        au.setNombres(autor);
        
        Libro libro;
        if (jComboBoxTipo.getSelectedIndex()==0){
           //String tipopasta= this.buttonGroupTipoPasta.getSelection().toString();
            String tippast="";
            if(this.jRadioButtonPastaDura.isSelected()){
                tippast= jRadioButtonPastaDura.getText();
            }
            else if (this.jRadioButtonPastaSuave.isSelected()){
                tippast= jRadioButtonPastaSuave.getText();
            }
            libro = new LibroImpreso(np, tippast, isbn, tit, 2018, 0, au);
            
        }
        else if (jComboBoxTipo.getSelectedIndex()==1) {
            double tamanio= (double) this.jSpinnerTamañoArchivo.getValue();
            boolean isInterac = this.jCheckBoxEsIteractivo.isSelected();
            String textoInt = "";
            
            if(isInterac){
                textoInt= this.jCheckBoxEsIteractivo.getText();
            }
            
            
            libro = new LibroElectronico(tamanio, isInterac, isbn, tit, np, 0, au);
        }
        else{
            libro = new LibroImpreso();
                }
        
        double precio = libro.calcularPrecio();
        
        JOptionPane.showMessageDialog(this, "El libro " + libro.toString());
        JOptionPane.showMessageDialog(this , "El precio del libro: " + precio);
    
        oper.agregar(libro);
        oper.guardarEnArchivo(libro);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNuevoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoPasta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JCheckBox jCheckBoxEsIteractivo;
    private javax.swing.JComboBox<String> jComboBoxAutorPrincipal;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelAutorPrincipal;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelNumPaginas;
    private javax.swing.JLabel jLabelPastaSeleccionada;
    private javax.swing.JLabel jLabelTamanoArchivo;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoDePasta;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelElectronico;
    private javax.swing.JPanel jPanelImpreso;
    private javax.swing.JRadioButton jRadioButtonPastaDura;
    private javax.swing.JRadioButton jRadioButtonPastaSuave;
    private javax.swing.JSpinner jSpinnerNumPaginas;
    private javax.swing.JSpinner jSpinnerTamañoArchivo;
    private javax.swing.JTextField jTextFieldInteractivo;
    private javax.swing.JTextField jTextFieldIsbn;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
